const data = [
        {
        "CRN": "18699",
        "Term": "Fall 2019",
        "Course": "DGM 1061",
        "Section": "1",
        "Course Title": "Motion Picture Editing",
        "Schedule Type": "Face to Face (F)",
        "Title": "",
        "Meeting Pattern": "MW 10am-11:50am",
        "Instructor": "Staff",
        "Building and Room": "CS 715B",
        "Part of Term": "Full Term (1)",
        "Credit Hrs Min": "3",
        "Maximum Enrollment": "28"
        },
        {
        "CRN": "28057",
        "Term": "Fall 2019",
        "Course": "DGM 1061",
        "Section": "2",
        "Course Title": "Motion Picture Editing",
        "Schedule Type": "Face to Face (F)",
        "Title": "",
        "Meeting Pattern": "MW 12pm-1:50pm",
        "Instructor": "Staff",
        "Building and Room": "CS 715B",
        "Part of Term": "Full Term (1)",
        "Credit Hrs Min": "3",
        "Maximum Enrollment": "28"
        },
    ];

    module.exports = [ data ];
        // {
        // "CRN": "",
        // "Term": "",
        // "Course": "",
        // "Section": "",
        // "Course Title": "",
        // "Schedule Type": "",
        // "Title": "",
        // "Meeting Pattern": "",
        // "Instructor": "",
        // "Building and Room": "",
        // "Part of Term": "",
        // "Credit Hrs Min": "",
        // "Maximum Enrollment": ""
        // },
        // {
        // "CRN": "26604",
        // "Term": "Fall 2019",
        // "Course": "DGM 1063",
        // "Section": "X01",
        // "Course Title": "Image Editing",
        // "Schedule Type": "Internet (W)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "ONLINE ONLINE",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "2",
        // "Maximum Enrollment": "35"
        // },
        // {
        // "CRN": "29630",
        // "Term": "Fall 2019",
        // "Course": "DGM 1063",
        // "Section": "X02",
        // "Course Title": "Image Editing",
        // "Schedule Type": "Internet (W)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "ONLINE ONLINE",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "2",
        // "Maximum Enrollment": "36"
        // },
        // {
        // "CRN": "",
        // "Term": "",
        // "Course": "",
        // "Section": "",
        // "Course Title": "",
        // "Schedule Type": "",
        // "Title": "",
        // "Meeting Pattern": "",
        // "Instructor": "",
        // "Building and Room": "",
        // "Part of Term": "",
        // "Credit Hrs Min": "",
        // "Maximum Enrollment": ""
        // },
        // {
        // "CRN": "16184",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "1",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "MW 8am-9:50am",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "30"
        // },
        // {
        // "CRN": "16185",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "2",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "TR 8am-9:50am",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "30"
        // },
        // {
        // "CRN": "16186",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "3",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "MW 12pm-1:50pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "30"
        // },
        // {
        // "CRN": "16187",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "4",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "MW 2pm-3:50pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "30"
        // },
        // {
        // "CRN": "19572",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "6",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "TR 3pm-4:50pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "30"
        // },
        // {
        // "CRN": "16188",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "601",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "MW 5:30pm-7:20pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "29"
        // },
        // {
        // "CRN": "21446",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "602",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "TR 5:30pm-7:20pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "29"
        // },
        // {
        // "CRN": "24866",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "603",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "MW 7:30pm-9:20pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "29"
        // },
        // {
        // "CRN": "25940",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "604",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "TR 7:30pm-9:20pm",
        // "Instructor": "Staff",
        // "Building and Room": "CS 512",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "29"
        // },
        // {
        // "CRN": "26951",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "760",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "R 5:30pm-8:50pm",
        // "Instructor": "Staff",
        // "Building and Room": "WC 219",
        // "Part of Term": "Full Term (1)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "22"
        // },
        // {
        // "CRN": "31176",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "H01",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "HSAF TBA",
        // "Part of Term": "HS Full Year (HSF)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "100"
        // },
        // {
        // "CRN": "16897",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "H17",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "HSOR TBA",
        // "Part of Term": "HS Full Year (HSF)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "100"
        // },
        // {
        // "CRN": "27857",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "H24",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "HSPA TBA",
        // "Part of Term": "HS Full Year (HSF)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "100"
        // },
        // {
        // "CRN": "17043",
        // "Term": "Fall 2019",
        // "Course": "DGM 1110",
        // "Section": "H29",
        // "Course Title": "Digital Media Essentials I",
        // "Schedule Type": "Face to Face (F)",
        // "Title": "",
        // "Meeting Pattern": "Does Not Meet",
        // "Instructor": "Staff",
        // "Building and Room": "HSPG TBA",
        // "Part of Term": "HS Full Year (HSF)",
        // "Credit Hrs Min": "4",
        // "Maximum Enrollment": "100"
        // }